src/ads/urls.py
from django.urls import path

from ads.apps import AdsConfig
from ads import views as ads_views

app_name = AdsConfig.name

urlpatterns = [
    path('', ads_views.main, name='main'),
    path('create/', ads_views.AdsCreateView.as_view(), name='ads-create'),
    path('list/', ads_views.AdsListView.as_view(), name='ads-list'),
    path('update/<int:pk>/', ads_views.AdsUpdateView.as_view(), name='ads-update'),
    path('delete/<int:pk>/', ads_views.AdsDeleteView.as_view(), name='ads-delete'),

    path('offer/create/<int:pk>/', ads_views.ExchangeProposalCreateView.as_view(), name='offer-create'),
    path('offer/list/', ads_views.ExchangeProposalListView.as_view(), name='offer-list'),
    path('offer/accept/<int:pk>/', ads_views.exchange_proposal_accept, name='offer-accept'),
    path('offer/reject/<int:pk>/', ads_views.exchange_proposal_reject, name='offer-reject'),
    path('offer/delete/<int:pk>/', ads_views.ExchangeProposalDeleteView.as_view(), name='offer-delete'),
]

src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace="users")),
    path('ads/', include('ads.urls', namespace="ads")),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

src/users/urls.py
from users.apps import UsersConfig
from django.urls import path
from .views import register
from django.contrib.auth import views as auth_views

app_name = UsersConfig.name

urlpatterns = [
    path('register/', register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

src/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from core import mixins


class RegisterForm(mixins.StyleFormMixin, UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

src/users/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('users:login')
    else:
        form = RegisterForm()
    return render(request, 'users/registration.html', {'form': form})

src/users/templates/users/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">


</head>

<body style="padding-top: 70;">

<div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
    <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
            id="bd-theme"
            type="button"
            aria-expanded="false"
            data-bs-toggle="dropdown"
            aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em">
            <use href="#circle-half"></use>
        </svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
    </button>
    <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50" width="1em" height="1em">
                    <use href="#sun-fill"></use>
                </svg>
                Light
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50" width="1em" height="1em">
                    <use href="#moon-stars-fill"></use>
                </svg>
                Dark
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto"
                    aria-pressed="true">
                <svg class="bi me-2 opacity-50" width="1em" height="1em">
                    <use href="#circle-half"></use>
                </svg>
                Auto
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
    </ul>
</div>


<nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark" aria-label="Main navigation">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'ads:ads-list' %}">Объявления</a>
        <a class="navbar-brand" href="{% url 'ads:offer-list' %}">Предложения</a>


        <div class="navbar-collapse offcanvas-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                {% if user.is_authenticated %}
                <li class="nav-item">
                    <form method="post" action="{% url 'ads:ads-create' %}">
                        {% csrf_token %}
                        <button class="btn 	btn-warning" type="submit">Создать</button>
                    </form>
                </li>

                <li class="nav-item">
                    <form method="post" action="{% url 'users:logout' %}">
                        {% csrf_token %}
                        <button class="btn btn-outline-primary" type="submit">Выйти</button>
                    </form>
                </li>


                {% else %}
                <li class="nav-item">
                    <a class="nav-link " href="{% url 'users:login' %}">Вход</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:register' %}">Регистрация</a>
                </li>
                {% endif %}

            </ul>
            <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Поиск</button>
            </form>
        </div>
    </div>
</nav>

{% block content %}
{% endblock %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</body>
</html>

src/users/templates/users/login.html
{% extends 'users/base.html' %}

{% block content %}
<div class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-header">Вход</div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Войти</button>
                </form>
            </div>
            <div class="card-footer"></div>
        </div>
    </div>
</div>
{% endblock %}

src/users/templates/users/registration.html
{% extends 'users/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header"></div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Зарегистрироваться</button>
                    </form>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
    </div>
</div>
{% endblock %}