src/ads/urls.py
from django.urls import path

from ads.apps import AdsConfig
from ads import views as ads_views

app_name = AdsConfig.name

urlpatterns = [
    path('', ads_views.main, name='main'),
    path('create/', ads_views.AdsCreateView.as_view(), name='ads-create'),
    path('list/', ads_views.AdsListView.as_view(), name='ads-list'),
    path('update/<int:pk>/', ads_views.AdsUpdateView.as_view(), name='ads-update'),
    path('delete/<int:pk>/', ads_views.AdsDeleteView.as_view(), name='ads-delete'),

    path('offer/create/<int:pk>/', ads_views.ExchangeProposalCreateView.as_view(), name='offer-create'),
    path('offer/list/', ads_views.ExchangeProposalListView.as_view(), name='offer-list'),
    path('offer/accept/<int:pk>/', ads_views.exchange_proposal_accept, name='offer-accept'),
    path('offer/reject/<int:pk>/', ads_views.exchange_proposal_reject, name='offer-reject'),
    path('offer/delete/<int:pk>/', ads_views.ExchangeProposalDeleteView.as_view(), name='offer-delete'),
]

src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace="users")),
    path('ads/', include('ads.urls', namespace="ads")),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

src/ads/models.py
from django.db import models
from core import constants, enums
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(
        max_length=constants.MAX_LENGTH_CATEGORY,
        verbose_name="Название"
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class Ads(models.Model):
    title = models.CharField(
        max_length=constants.MAX_LENGTH_ADS,
        verbose_name="Название"
    )
    description = models.TextField(
        verbose_name="Описание"
    )
    image_url = models.URLField(
        **constants.NULLABLE,
        verbose_name="Ссылка на фото"
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        verbose_name="Категории",
        related_name="ads"
    )
    condition = models.CharField(
        max_length=constants.MAX_LENGTH_COMMENT,
        choices=enums.ConditionEnums.choices,
        verbose_name="Состояние"
    )
    owner = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="abs",
        **constants.NULLABLE
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Дата создания"
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name="Дата обновления"
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Объявление'
        verbose_name_plural = 'Объявления'


class ExchangeProposal(models.Model):
    ad_sender = models.ForeignKey(
        Ads,
        on_delete=models.CASCADE,
        verbose_name="Объявление отправителя",
        related_name="sent_exchange_proposals"
    )
    ad_receiver = models.ForeignKey(
        Ads,
        on_delete=models.CASCADE,
        verbose_name="Объявление получателя",
        related_name="received_exchange_proposals"
    )
    comment = models.CharField(
        max_length=constants.MAX_LENGTH_COMMENT,
        verbose_name="Комментарий",
        **constants.NULLABLE
    )
    status = models.CharField(
        max_length=constants.MAX_LENGTH_CHOICES,
        choices=enums.StatusEnums.choices,
        default=enums.StatusEnums.WAITING,
        verbose_name="Статус"
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Дата создания"
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name="Дата Обновления"
    )

    def __str__(self):
        return f"Статус: {self.status} Отправитель: {self.ad_sender.owner} Получатель: {self.ad_receiver.owner}"

    class Meta:
        verbose_name = "Предложение"
        verbose_name_plural = "Предложения"

src/ads/forms.py
from django import forms
import ads.models as ads_models
from core import mixins


class AdsCreateForm(mixins.StyleFormMixin, forms.ModelForm):
    class Meta:
        model = ads_models.Ads
        fields = (
            "title",
            "description",
            "image_url",
            "category",
            "condition",
        )


class ExchangeProposalForm(mixins.StyleFormMixin, forms.ModelForm):
    class Meta:
        model = ads_models.ExchangeProposal
        fields = ("ad_sender", "comment")

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        if user:
            self.fields['ad_sender'].queryset = ads_models.Ads.objects.filter(owner=user)

src/ads/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import Http404
from django.urls import reverse_lazy
from django.views import generic
import ads.models as ads_models
import ads.forms as ads_forms
import core.enums
from core import mixins
from django.shortcuts import render, get_object_or_404, redirect


def main(request):
    return render(request, 'ads/main.html')


class AdsCreateView(LoginRequiredMixin, generic.CreateView):
    model = ads_models.Ads
    form_class = ads_forms.AdsCreateForm
    template_name = 'ads/ads_form.html'
    success_url = reverse_lazy('ads:ads-list')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class AdsListView(LoginRequiredMixin, generic.ListView):
    model = ads_models.Ads
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        query = self.request.GET.get('q')
        category = self.request.GET.get('category')
        condition = self.request.GET.get('condition')

        if query:
            queryset = queryset.filter(
                Q(title__icontains=query) | Q(description__icontains=query)
            )
        if category:
            queryset = queryset.filter(category=category)
        if condition:
            queryset = queryset.filter(condition=condition)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = ads_models.Category.objects.all()
        context['condition'] = core.enums.ConditionEnums.choices
        return context


class AdsUpdateView(LoginRequiredMixin, mixins.OwnerOrSuperuserRequiredMixin, generic.UpdateView):
    model = ads_models.Ads
    form_class = ads_forms.AdsCreateForm
    template_name = 'ads/ads_form.html'
    success_url = reverse_lazy('ads:ads-list')


class AdsDeleteView(LoginRequiredMixin, mixins.OwnerOrSuperuserRequiredMixin, generic.DeleteView):
    model = ads_models.Ads
    success_url = reverse_lazy("ads:ads-list")


class ExchangeProposalCreateView(LoginRequiredMixin, generic.CreateView):
    model = ads_models.ExchangeProposal
    form_class = ads_forms.ExchangeProposalForm
    template_name = 'ads/ads_form.html'
    success_url = reverse_lazy('ads:ads-list')

    def dispatch(self, request, *args, **kwargs):
        try:
            self.ad_receiver = ads_models.Ads.objects.get(pk=kwargs['pk'])
        except ads_models.Ads.DoesNotExist:
            raise Http404("Ad not found")
        return super().dispatch(request, *args, **kwargs)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        # ❗ Проверка на попытку обмена своим же объявлением
        if self.ad_receiver.owner == self.request.user:
            form.add_error(None, "Нельзя обменивать свои собственные объявления.")
            return self.form_invalid(form)

        form.instance.ad_receiver = self.ad_receiver
        return super().form_valid(form)


class ExchangeProposalListView(LoginRequiredMixin, generic.ListView):
    model = ads_models.ExchangeProposal
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        filters = {}

        status = self.request.GET.get("status")
        ad_sender = self.request.GET.get("ad_sender")
        ad_receiver = self.request.GET.get("ad_receiver")

        if status:
            filters["status"] = status
        if ad_sender:
            filters["ad_sender_id"] = ad_sender
        if ad_receiver:
            filters["ad_receiver_id"] = ad_receiver

        return queryset.filter(**filters)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user

        context["statuses"] = core.enums.StatusEnums.choices

        context["ad_receivers"] = ads_models.ExchangeProposal.objects.filter(ad_sender__owner=user)  # кому я отправил
        context["ad_senders"] = ads_models.ExchangeProposal.objects.filter(ad_receiver__owner=user)  # кто мне отправил

        return context


class ExchangeProposalDeleteView(LoginRequiredMixin, mixins.SenderOrSuperuserMixin, generic.DeleteView):
    model = ads_models.ExchangeProposal
    template_name = "ads/ads_confirm_delete.html"
    success_url = reverse_lazy("ads:offer-list")
    raise_exception = True


@login_required
def exchange_proposal_accept(request, pk):
    proposal = get_object_or_404(ads_models.ExchangeProposal, pk=pk)
    proposal.status = core.enums.StatusEnums.ACCEPTED
    proposal.save()
    return redirect("ads:offer-list")


@login_required
def exchange_proposal_reject(request, pk):
    proposal = get_object_or_404(ads_models.ExchangeProposal, pk=pk)
    proposal.status = core.enums.StatusEnums.REJECTED
    proposal.save()
    return redirect("ads:offer-list")

src/ads/templates/ads/ads_confirm_delete.html
{% extends 'users/base.html' %}
{% block content %}
<div class="container">
    <main>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row g-5">
                <div class="col-md-7 col-lg-8">
                    <h4 class="mb-3">Удаление</h4>
                    <form class="needs-validation" novalidate>

                        <hr class="my-4">
                        <p>Вы действительно хотите удалить?</p>

                        <button class="btn btn-danger btn-lg" type="submit">Удалить</button>
                        <a href="{% url 'ads:ads-list' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </form>
    </main>
</div>
{% endblock %}

src/ads/templates/ads/ads_form.html
{% extends 'users/base.html' %}
{% block content %}

<div class="container">
    <main>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row g-5">

                <div class="col-md-7 col-lg-8">

                    <h4 class="mb-3">{% if object %}
                            Редактирование
                            {% else %}
                            Создание
                            {% endif%}</h4>
                    <form class="needs-validation" novalidate>
                        {{ form.as_p }}

                        <hr class="my-4">

                        <button class="w-100 btn btn-primary btn-lg" type="submit">
                            {% if object %}
                            Сохранить
                            {% else %}
                            Создать
                            {% endif%}
                        </button>
                    </form>

                </div>
            </div>
        </form>
    </main>
</div>

{% endblock %}

src/ads/templates/ads/ads_list.html
{% extends 'users/base.html' %}
{% block content %}

<div class="my-3 p-3 bg-body rounded shadow-sm">

    <form method="get" class="d-flex gap-2 mb-3">
        <input type="text" name="q" placeholder="Поиск..." class="form-control" value="{{ request.GET.q }}">

        <select name="category" class="form-select">
            <option value="">Все категории</option>
            {% for cat in categories %}
            <option value="{{ cat.id }}" {% if request.GET.category == cat.id|stringformat:"s" %}selected{% endif %}>
            {{ cat.name }}
            </option>
            {% endfor %}
        </select>

        <select name="condition" class="form-select">
            <option value="">Все состояния</option>
            {% for key, label in condition %}
            <option value="{{ key }}" {% if request.GET.condition == key %}selected{% endif %}>{{ label }}</option>
            {% endfor %}
        </select>

        <button type="submit" class="btn btn-primary">Найти</button>
    </form>
    <h6 class="border-bottom pb-2 mb-0">Объявления</h6>


    {% for object in object_list %}
    <div class="d-flex text-body-secondary pt-3">

        <div class="pb-3 mb-0 small lh-sm border-bottom w-100">
            <div class="d-flex justify-content-between">
                <strong class="text-gray-dark">Объявление: {{ object.pk }}</strong>
            </div>
            <div class="d-flex justify-content-between">
                <strong class="text-gray-dark">Объявление: {{ object.title }}</strong>
            </div>
            <div class="d-flex justify-content-between">
                <strong class="text-gray-dark">Категория: {{ object.category }}</strong>
            </div>
            <div class="d-flex justify-content-between">
                <strong class="text-gray-dark">Состояние: {{ object.condition }}</strong>
            </div>
            <div class="d-flex justify-content-between">
                <strong class="text-gray-dark">Дата публикации: {{ object.created_at.date }}</strong>
            </div>
            <div class="d-flex justify-content-between">
                <strong class="text-gray-dark">Фото: {{ object.image_url }}</strong>
            </div>
            <div class="d-flex justify-content-between">
                <strong class="text-gray-dark">Собственник: {{ object.owner }}</strong>
            </div>

            <div class="mt-2">
                <div class="d-flex justify-content-between">
                    <strong class="text-gray-dark">Описание: {{ object.description|truncatechars:50 }}</strong>
                </div>
            </div>
        </div>

        <div>
            {% if user == object.owner %}
            <a href="{% url 'ads:ads-update' object.pk %}"
               class="btn btn-lg btn-block btn-outline-primary">Редактировать</a>
            <a href="{% url 'ads:ads-delete' object.pk %}"
               class="btn btn-lg btn-block btn-outline-primary">удалить</a>
            {% else %}
            <a href="{% url 'ads:offer-create' object.pk %}"
               class="btn btn-lg btn-block btn-outline-primary">Предложить</a>
            {% endif %}

        </div>
        <div class="d-flex justify-content-end"></div>
    </div>
    {% endfor%}
</div>

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; первая</a>
            <a href="?page={{ page_obj.previous_page_number }}">назад</a>
        {% endif %}

        <span class="current">
            Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">вперёд</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">последняя &raquo;</a>
        {% endif %}
    </span>
</div>

{% endblock %}

src/ads/templates/ads/exchangeproposal_list.html
{% extends 'users/base.html' %}
{% block content %}

<div class="my-3 p-3 bg-body rounded shadow-sm">

    <form method="get" class="d-flex gap-2 mb-3">

        <select name="ad_receiver" class="form-select">
            <option value="">Все получатели</option>
            {% for cat in ad_receivers %}
            <option value="{{ cat.id }}" {% if request.GET.ad_receiver == cat.id|stringformat:"s" %}selected{% endif %}>
            {{ cat.ad_receiver.owner }}
            </option>
            {% endfor %}
        </select>

        <select name="ad_sender" class="form-select">
            <option value="">Все отправители</option>
            {% for cat in ad_senders %}
            <option value="{{ cat.id }}" {% if request.GET.ad_sender == cat.id|stringformat:"s" %}selected{% endif %}>
            {{ cat.ad_sender.owner }}
            </option>
            {% endfor %}
        </select>

        <select name="status" class="form-select">
            <option value="">Все статусы</option>
            {% for key, label in statuses %}
            <option value="{{ key }}" {% if request.GET.status == key %}selected{% endif %}>{{ label }}</option>
            {% endfor %}
        </select>

        <button type="submit" class="btn btn-primary">Найти</button>
    </form>
    <h6 class="border-bottom pb-2 mb-0">Предложения</h6>


    {% for object in object_list %}
    <div class="d-flex text-body-secondary pt-3">

        <div class="pb-3 mb-0 small lh-sm border-bottom w-100">
            <div class="d-flex justify-content-between">
                <strong class="text-gray-dark">Инициатор: {{ object.ad_sender.owner }}</strong>
            </div>
            <div class="d-flex justify-content-between">
                <strong class="text-gray-dark">Получатель: {{ object.ad_receiver.owner }}</strong>
            </div>
            <div class="d-flex justify-content-between">
                <strong class="text-gray-dark">Получу: {{ object.ad_sender }}</strong>
            </div>
            <div class="d-flex justify-content-between">
                <strong class="text-gray-dark">Отдам: {{ object.ad_receiver }}</strong>
            </div>
            <div class="d-flex justify-content-between">
                <strong class="text-gray-dark">Комментарий: {{ object.comment }}</strong>
            </div>
            <div class="d-flex justify-content-between">
                <strong class="text-gray-dark">Фото: {{ object.status }}</strong>
            </div>
            <div class="d-flex justify-content-between">
                <strong class="text-gray-dark">Дата публикации: {{ object.created_at.date }}</strong>
            </div>
        </div>

        <div>
            {% if user == object.ad_sender.owner or user.is_superuser %}
            <a href="{% url 'ads:offer-delete' object.pk %}"
               class="btn btn-lg btn-block btn-outline-primary">удалить</a>
            {% else %}
            <a href="{% url 'ads:offer-reject' object.pk %}"
               class="btn btn-lg btn-block btn-outline-primary">Отменить</a>
            <a href="{% url 'ads:offer-accept' object.pk %}"
               class="btn btn-lg btn-block btn-outline-primary">Принять</a>
            {% endif %}

        </div>
        <div class="d-flex justify-content-end"></div>
    </div>
    {% endfor%}
</div>

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; первая</a>
            <a href="?page={{ page_obj.previous_page_number }}">назад</a>
        {% endif %}

        <span class="current">
            Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">вперёд</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">последняя &raquo;</a>
        {% endif %}
    </span>
</div>

{% endblock %}

src/ads/templates/ads/main.html
{% extends 'users/base.html' %}
{% block content%}
{% endblock %}